[project]
name = "gear-guide"
version = "0.1.0"
dependencies = [
    "flask == 3.1.2",
    "python-dotenv == 1.2.1",
    "flask_sqlalchemy == 3.1.1",
    "flask_migrate == 4.1.0",
    "flask_login == 0.6.3",
    "requests == 2.32.5"
]

[tool.setuptools]
packages = ["GearGuide"]